/**
 * AI360 – Shared Enumerations
 * Used across dashboard, backend (via OpenAPI), and VS Code extension.
 */

/** User roles enforced by RBAC throughout the platform */
export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  ADMIN = 'ADMIN',
  EXECUTIVE = 'EXECUTIVE',
}

/** Prompt categories classified by the Prompt Intelligence Engine */
export enum PromptCategory {
  CODING = 'CODING',
  SQL = 'SQL',
  EMAIL = 'EMAIL',
  DOCUMENTATION = 'DOCUMENTATION',
  RESEARCH = 'RESEARCH',
  DEBUGGING = 'DEBUGGING',
  ARCHITECTURE = 'ARCHITECTURE',
  TRANSLATION = 'TRANSLATION',
  MEETING_NOTES = 'MEETING_NOTES',
  SUMMARIZATION = 'SUMMARIZATION',
  OTHER = 'OTHER',
}

/** Supported AI provider adapters */
export enum AIProvider {
  OPENAI = 'OPENAI',
  GEMINI = 'GEMINI',
  CLAUDE = 'CLAUDE',
}

/** AI model identifiers */
export enum AIModel {
  // OpenAI
  GPT_4O = 'gpt-4o',
  GPT_4O_MINI = 'gpt-4o-mini',
  GPT_4_TURBO = 'gpt-4-turbo',
  GPT_35_TURBO = 'gpt-3.5-turbo',
  // Google Gemini
  GEMINI_15_PRO = 'gemini-1.5-pro',
  GEMINI_15_FLASH = 'gemini-1.5-flash',
  GEMINI_20_FLASH = 'gemini-2.0-flash',
  // Anthropic Claude
  CLAUDE_35_SONNET = 'claude-3-5-sonnet-20241022',
  CLAUDE_3_HAIKU = 'claude-3-haiku-20240307',
  CLAUDE_3_OPUS = 'claude-3-opus-20240229',
}

/** Types of recommendations generated by the Recommendation Engine */
export enum RecommendationType {
  BETTER_PROMPT = 'BETTER_PROMPT',
  BETTER_MODEL = 'BETTER_MODEL',
  ESTIMATED_SAVINGS = 'ESTIMATED_SAVINGS',
  LEARNING = 'LEARNING',
  DEPARTMENT = 'DEPARTMENT',
  ORGANIZATION = 'ORGANIZATION',
}

/** Priority levels for recommendations and notifications */
export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

/** Sensitive data types detected by the PII scanner */
export enum SensitiveDataType {
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  API_KEY = 'API_KEY',
  SECRET_TOKEN = 'SECRET_TOKEN',
  URL_WITH_CREDENTIALS = 'URL_WITH_CREDENTIALS',
  PII_SSN = 'PII_SSN',
  PII_CREDIT_CARD = 'PII_CREDIT_CARD',
  PII_PHONE = 'PII_PHONE',
}

/** Notification types */
export enum NotificationType {
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  BUDGET_WARNING = 'BUDGET_WARNING',
  NEW_RECOMMENDATION = 'NEW_RECOMMENDATION',
  PROMPT_WARNING = 'PROMPT_WARNING',
  DAILY_SUMMARY = 'DAILY_SUMMARY',
  SYSTEM = 'SYSTEM',
}

/** Report export formats */
export enum ReportFormat {
  PDF = 'pdf',
  EXCEL = 'excel',
  CSV = 'csv',
}

/** Report types */
export enum ReportType {
  EMPLOYEE = 'employee',
  DEPARTMENT = 'department',
  ORGANIZATION = 'organization',
  MONTHLY = 'monthly',
  ROI = 'roi',
}
